name: "Bug report"
about: Create a report to help us improve
title: "[Report]"
labels: [
  "bug"
]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Which device were you using?
      options:
        - Windows
        - Linux
        - MacOS
        - Android
        - IOS
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - v0.1.1
        - v0.1.0
    validations:
      required: true
