name: "Bug report"
description: Create a report to help us improve
title: "[Report]"
labels: [
  "bug"
]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
        - type: dropdown
    id: device
    attributes:
      label: Device
      description: Which device were you using?
      options:
        - Windows
        - Linux
        - MacOS
        - Android
        - IOS
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - v0.1.1
        - v0.1.0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Would you be of sposte to implement it yourself?
      description: Support is very important to us. (Also consider your skills)
      options:
        - label: Yes I want to help
          required: false

  - type: textarea
    id: additional-description
    attributes:
      label: Additional Description
      description: Add a description to help us understand
      placeholder: Description
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
