blank_issues_enabled: false
contact_links:
  - name: 'Discussion'
    url: https://github.com/DRincs-Productions/ABFD/discussions
    about: 'For Discussion and Ask'
  - name: 'Writing or Translation'
    url: https://github.com/DRincs-Productions/ABFD-writing/issues/new/choose
    about: 'For issues relating to the Writing or Translation'
  - name: 'WebSite or Support'
    url: https://github.com/DRincs-Productions/drincs-website/issues/new/choose
    about: 'For issues relating to the WebSite or Support'
  - name: 'Discord'
    url: https://github.com/DRincs-Productions/drincs-discord-bot/issues/new/choose
    about: 'For issues relating to the Discord'
  - name: 'Daz Assert Issues'
    url: https://github.com/DRincs-Productions/daz-assert-ABFD-all-in-one/issues/new/choose
    about: 'Dedicated only for 3D developers'
