name: Quest
description: Suggest an Quest/mission for this project
title: "[Draft]"
labels: quest
body:
  - type: textarea
    id: description
    attributes:
      label: Explanation and instructions
      description: If you link a public word file, it is better. Respect the legend below.
      placeholder: [Word file](https://onedrive.live.com/#################)
    validations:
      required: true
  - type: textarea
    id: language
    attributes:
      label: Language used for dialogues
      description: I suggest using your native language in dialogues, while for notes you must use English
      placeholder: English or Italian or French ...
    validations:
      required: true
  - type: textarea
    id: legend
    attributes:
      label: Legend
      description: Change the recommended legend only in special cases
      value:"| Text Color | Type  | Description | Requirements |
| ------------- | ------------- | ------------- | ------------- |
| ⚫Black 🖋️ | General  | Explanations of the events and acts that follow. |Divide the various acts by titles. Detailed explanations. Acts should be in chronological order and explain where there are ramifications.  |
| 🟩Green 🖋️ | 3D Development | Explanation of images to be shown at that time| Number of images to be shown in that act  |
| 🔵Blue 🖋️ | Writing | Everything the characters will say and think at that time | In front of each sentence there must be the name of who is speaking (e.g. Bob: Hello Guys ).   In italics what the characters will think (e.g. Bob: _Mhh... I should check the phone_ ).    the menu choices are bulleted lists.  |
| 🟪Purple 🖋️  | Note | Notes and Advice  | | 
| 🔴Red - **Highlighter** 🖍️ | Errors | Report errors and unclear elements | Fold in any doubts, errors, and inaccuracies.|"
    validations:
      required: true
  - type: textarea
    id: status
    attributes:
      label: Status and stages of development
      description: Remove what does not require this development
      value: "- [ ] ✏️Writeng: in broad strokes
- [ ] 📷 3D: Posing
- [ ] 📷 3D: Complete the scene
- [ ] 🎨 Art: Rendering
- [ ] ✏️Writeng: Dialogues
- [ ] 💻 Coding"
    validations:
      required: true
